### PR TITLE
Use feather file/query objects

### PR DESCRIPTION
**Pull request by johnbradley**

### CODE REVIEW

**Comment by johnbradley** [comment]
@matthewhirschey The version was increased to 0.2.14 in these changes. Is this sufficient or should i increment it again before merging these changes?

**Comment by johnbradley** [comment]
The automated builds are failing with
```
The error most likely occurred in:
> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: colorRampPalette_shuffle
> ### Title: Function to generate shuffled colors based on 'colorRampPalette'
> ### Aliases: colorRampPalette_shuffle
> 
> ### ** Examples
> 
> colorRampPalette_shuffle(colors = c("#DEBBF4", "#BE34EF", "#AC7B84"))
Error in colorRampPalette_shuffle(colors = c("#DEBBF4", "#BE34EF", "#AC7B84")) : 
  could not find function "colorRampPalette_shuffle"
```

**Comment by johnbradley** [comment]
The errors are occurring trying to run the examples for various functions. The initial problem is that the functions are not exported in NAMESPACE. I tried adding "colorRampPalette_shuffle" to NAMESPACE and then had the same error for "generate_colors". After adding "generate_colors" there was an error on `get_essential`:
```
NoSuchKey (HTTP 404). The specified key does not exist.
```
I think this is because the environment isn't setup.
Perhaps we shouldn't be testing some of these examples via Github Actions.
Instead of trying to fix this issue in this PR I am going to create an issue to address later.

**Comment by matthewhirschey** [comment]
> @matthewhirschey The version was increased to 0.2.14 in these changes. Is this sufficient or should i increment it again before merging these changes?

Should be OK, given these were not merged. So the merge will increment the version, and that will allow us to update the package when we re-install.

**Comment by matthewhirschey** [comment]
> The errors are occurring trying to run the examples for various functions. The initial problem is that the functions are not exported in NAMESPACE. I tried adding "colorRampPalette_shuffle" to NAMESPACE and then had the same error for "generate_colors". After adding "generate_colors" there was an error on `get_essential`:
> 
> ```
> NoSuchKey (HTTP 404). The specified key does not exist.
> ```
> 
> I think this is because the environment isn't setup. Perhaps we shouldn't be testing some of these examples via Github Actions. Instead of trying to fix this issue in this PR I am going to create an issue to address later.

Yes, we will need to figure out the best strategy to make a query object available to the package (similar to the old "test" data) that GH actions can also use for testing. One idea: we might drop ROCK1 and ROCK2 feather files into the package as data. And then add some logic to access it if "NoSuchKey (HTTP 404). The specified key does not exist." or something.

**Pull request merged**
